### ISSUE TITLE
deploy.ps1 fails: cannot find Microsoft.Web/ resource

### ISSUE THREAD

**Issue by markjbrown** [AzureCosmosDB/scenario-based-labs#10]
Getting this error on line 62 for  deploy.ps1 

![image](https://user-images.githubusercontent.com/800166/66680589-bf5d0400-ec25-11e9-902d-6e0db52cae8d.png)

**Comment by markjbrown** [comment]
Best I can tell this line is what failed after labDeploy5.json ran.

#need the suffix...
if ($deployment.properties.provisioningState -eq "Succeeded")
{
    $suffix = $deployment.properties.outputs.hash.value
}

**Comment by givenscj** [comment]
There may be some other failure in your subscription.  You'll need to check the ARM template deployment steps for any errors.  I have seen throttles in MSFT subs that stop you from deploying more app webs.

**Comment by givenscj** [comment]
When you retry, if you still have an issue, please refile with a screenshot/copy of the ARM deployment errors from the Azure Portal.
