### ISSUE TITLE
Creation of KeyVault fails

### ISSUE THREAD

**Issue by markjbrown** [AzureCosmosDB/scenario-based-labs#11]
The set secret calls to Keyvault all failed. It appears the key vault resource was not created as it is not in the created resource group. 

Setting key vault values...
az : ERROR: az keyvault secret set: error: argument --vault-name: expected one argument
At C:\cosmos-db-scenario-based-labs-master\Retail\deploy\deploy.ps1:666 char:10
+ $res = $(az keyvault secret set --vault-name $keyvault.Name --name "p ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: az keyva...ed one argument:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
usage: az keyvault secret set [-h] [--verbose] [--debug]
                              [--output {json,jsonc,table,tsv,yaml,none}]
                              [--query JMESPATH]
                              [--subscription _SUBSCRIPTION] --vault-name NAME
                              --name SECRET_NAME [--value VALUE]
                              [--tags [TAGS [TAGS ...]]]
                              [--description CONTENT_TYPE]
                              [--disabled [{true,false}]] [--expires EXPIRES]
                              [--not-before NOT_BEFORE] [--file FILE_PATH]
                              [--encoding {utf-8,utf-16le,utf-16be,ascii,base64,hex}]

**Comment by givenscj** [comment]
Two values would always fail in original script, added a function to check for blank values.  If key vault doesn't get created, you'll need to check the ARM template deployment for errors.

**Comment by givenscj** [comment]
Added the method to check for empty values and skip.  No errors should display unless the key vault did not get created.
