### ISSUE TITLE
Better explanation of querying for top purchased items in Retail lab

### ISSUE THREAD

**Issue by deborahc** [AzureCosmosDB/scenario-based-labs#12]
The current wording, in this [section](https://github.com/solliancenet/cosmos-db-scenario-based-labs/blob/master/Retail/HOL%20step-by-step%20-%20Cosmos%20DB%20scenario-based%20labs%20-%20Retail.md#task-1-implement-the-top-items-recommendation)

This code is responsible for querying the Cosmos DB object table to find the item aggregation information, for example all the buy events for a movie. It is important that you utilize aggregations to do this as Cosmos Db will charge you based on RUs. If you were to query the events table which is expected to get incredibly large as your user count and activity increaes, you can imagine the costs for making this query can become incredibly expensive.

Feedback
- In the context of Cosmos DB, we should not refer to Cosmos DB collections as "tables," as they are not tables in the relational sense. Replace with "collection.:
- We should be more precise on the statement "Cosmos DB will charge you based on RUs." It's more accurate to say something along the lines of, "Each operation in Cosmos DB consumes a certain amount of RUs. For queries, the RU charge is based on the number of documents returned, the complexity of the query, and the number of partitions queried. To continue to have efficient queries as user count and activity increases, we create an aggregated view...."
- Nit: typo on word increase
- Nit: All instances of Cosmos Db -> Cosmos DB

**Comment by givenscj** [comment]
Thanks, great suggestions!  Changes made!
