### ISSUE TITLE
Why have Subscription Name

### ISSUE THREAD

**Issue by markjbrown** [AzureCosmosDB/scenario-based-labs#16]
I made a typo for my subscription name in this deploy.ps1 and it threw this error. But the script appears to be running normally.

So why have it in here at all?

az : ERROR: The subscription of 'ycosmosdb-demos-generaluse' doesn't exist in cloud 'AzureCloud'.
At C:\scenario-based-labs-master\Retail\deploy\deploy.ps1:525 char:5
+     az account set --subscription $subName;
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: The subs...d 'AzureCloud'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by givenscj** [comment]
I removed it and only use subscription id now for switching.
