### ISSUE TITLE
KeyVault Not Provisioned

### ISSUE THREAD

**Issue by markjbrown** [AzureCosmosDB/scenario-based-labs#19]
Got same error again with KeyVault. I think this needs to be debugged further. I have repro'd this on every try with the same results.

Setting key vault values...
Setting AzureQueueConnectionString to DefaultEndpointsProtocol=https;AccountName=s2data3b6f53yxka32uw;AccountKey=6BJ2JvUx4TT5hjLSo/MGgqXqgHewR3pOKHhvU+oqnlGmNuN3NFQJJEdkyHGWS/WJjJA6KAMleyJJKl
q9e5F2iw==;EndpointSuffix=core.windows.net
az : ERROR: az keyvault secret set: error: argument --vault-name: expected one argument
At C:\scenario-based-labs-master\Retail\deploy\deploy.ps1:72 char:18
+ ...    $res = $(az keyvault secret set --vault-name $kvName --name $name  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: az keyva...ed one argument:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
usage: az keyvault secret set [-h] [--verbose] [--debug]
                              [--output {json,jsonc,table,tsv,yaml,none}]
                              [--query JMESPATH]
                              [--subscription _SUBSCRIPTION] --vault-name NAME
                              --name SECRET_NAME [--value VALUE]
                              [--tags [TAGS [TAGS ...]]]
                              [--description CONTENT_TYPE]
                              [--disabled [{true,false}]] [--expires EXPIRES]
                              [--not-before NOT_BEFORE] [--file FILE_PATH]
                              [--encoding {utf-8,utf-16le,utf-16be,ascii,base64,hex}]

**Comment by markjbrown** [comment]
I'm getting on a plane to Japan in a few hours so can't pair up with you now but will take another drop of this and run through it again Wednesday. Thanks Chris.

**Comment by givenscj** [comment]
This has been resolved in the new ARM templates and script.
