### ISSUE TITLE
IoT Lab: Exercise 9 Task 2- Running batch scoring notebook fails

### ISSUE THREAD

**Issue by timsander1** [AzureCosmosDB/scenario-based-labs#24]
Cmd 2 fails with error message: "Python interpreter is not defined for ReplId-44c00-bd47e-33a9b". Rest of notebook can't be executed until Cmd 2 can be executed

**Comment by joelhulen** [comment]
That is a strange error. Do you have an environment set up that I can connect to and take a look?

**Comment by joelhulen** [comment]
I would also try restarting the cluster. If that doesn't work, try creating a new one (and adding the Cosmos DB Spark connector library to it) and trying again. Also, please verify the Databricks version (LTS 5.5) of the cluster and that Python3 is selected.

**Comment by joelhulen** [comment]
Fixed the problem by pinning a specific version of the Azure ML SDK.

**Comment by myamama** [comment]
try this->
dbutils.library.installPyPI('azureml-sdk', version='1.15.0', extras='automl_databricks')
