### ISSUE TITLE
Suppress AZ CLI Warning during PS script execution.

### ISSUE THREAD

**Issue by markjbrown** [AzureCosmosDB/scenario-based-labs#3]
If possible it might be helpful to users to suppress this warning as it may confuse them.

PS C:\Users\markjbrown> C:\cosmos-db-scenario-based-labs-master\Retail\deploy\deploy.ps1
az : WARNING: The behavior of this command has been altered by the following extension: azure-ml-admin-cli
At C:\cosmos-db-scenario-based-labs-master\Retail\deploy\deploy.ps1:393 char:8
+ $res = az login;
+        ~~~~~~~~
    + CategoryInfo          : NotSpecified: (WARNING: The be...re-ml-admin-cli:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
WARNING: Note, we have launched a browser for you to login. For old experience with device code, use "az login --use-device-code"
WARNING: You have logged in. Now let us find all the subscriptions to which you have access...

**Comment by givenscj** [comment]
I don't see anyway to do this in the az login CLI command.  You might need to create a request on your side to the CLI team for this.

**Comment by markjbrown** [comment]
ack. will close.
