### ISSUE TITLE
[Retail] Exercise 1 Task 4 Step 4: Suggestion - Clarify instructions

### ISSUE THREAD

**Issue by falloutxAY** [AzureCosmosDB/scenario-based-labs#40]
This sentence can be improved to improve clarity. 
> NOTE: You must have waited for the Event Generator Databricks notebook to complete for this to run and have the later steps in the lab match.

Not sure if I understood fully what it is meant, but suggest to change it to something like below. 
> NOTE: You must wait for the Event Generator Databricks notebook to be completed first before running this step. This is to ensure that later steps in the lab to match.

Also, I suggest the above note is written on the first line of Step 4. i.e before 
> Press F5 to run the project.

**Comment by givenscj** [comment]
Updated.
