### ISSUE TITLE
[Retail] Exercise 3, Task 2 : Verify if I am on the right track

### ISSUE THREAD

**Issue by falloutxAY** [AzureCosmosDB/scenario-based-labs#42]
As compared to the lab guide, I have the below. It seems that my result set is way smaller than lab results. It that right? If not, can we put some verification steps to check so that the participants do not go on and only realized that they have done something incorrectly. 

![Capture2](https://user-images.githubusercontent.com/19646001/67732389-248e6300-fa36-11e9-86e3-fd762103d721.JPG)

**Comment by givenscj** [comment]
Hi there,

Yes, this is what the current lab outputs.  There was a point when it outputted much more but we scaled it back.  Added a note that you will see 8 items.
