### ISSUE TITLE
[Retail] Functions deployment problem

### ISSUE THREAD

**Issue by TheovanKraay** [AzureCosmosDB/scenario-based-labs#46]
When I went through lab instructions (as of yesterday). Deployment scripts do not appear to change variables relating to function in app web config, and even when changing manually, local.settings.json (or remote version) is not picked up, so function call returns no results from web app when deployed. Could fix manually by hard coding all the variables but suspect deployment scripts and paths need review.

**Comment by joelhulen** [comment]
@TheovanKraay Can you please tell me which scenario this is? Retail or IoT.

**Comment by joelhulen** [comment]
Could you please let me know which variables you set in the deployment script? Of course, be sure to remove secrets like your subscription id.

**Comment by TheovanKraay** [comment]
Hi, Retail.

Kind regards,

Theo
________________________________

**Comment by TheovanKraay** [comment]
$githubPath = "C:\scenario-based-labs-master”
$mode = "lab"  
$subscriptionId = "**" #
$prefix = "tvk"
$isSpektra = $false 
$databaseId = "movies"
$movieApiKey = "**"

**Comment by joelhulen** [comment]
What was the KeyVault value set to?

@givenscj Do you have time to look into this issue?

**Comment by TheovanKraay** [comment]
Sorry, set to false.

Kind regards,

Theo
________________________________

**Comment by TheovanKraay** [comment]
Just to add. The issue I am seeing is with functions and wep app not picking up Application settings when deployed to app service. The below settings are not picked up (as a result the web app does not display recommendations at the completion of Exercise 2 as expected):

In Function (FuncRecommend.cs):

RecommendationHelper.databaseId = config["databaseId"];
RecommendationHelper.endpointUrl = config["dbConnectionUrl"];
RecommendationHelper.authorizationKey = config["dbConnectionKey"];

In Web App (RecommendationHelper.cs):

string funcUrl = ConfigurationManager.AppSettings["funcAPIUrl"];

My environment: 

dotnet version: 2.2.402
Azure CLI: 2.0.76
Visual Studio 2019 (16.2.5)
Powershell:
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  145

**Comment by givenscj** [comment]
I ran the script with the same settings and had no issues.  I would check if your subscription deployment had an error around resource throttling.  That's the only thing I could think would stop the values from getting set.
