### ISSUE TITLE
Force users to update az cli

### ISSUE THREAD

**Issue by markjbrown** [AzureCosmosDB/scenario-based-labs#5]
Customers are unlikely to have the latest CLI on their machines. I would change the docs and have them run the cli install from the powershell ISE before starting the PS deploy script.

Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'

Not installing the latest CLI generates this error when attempting to get the cosmosdb account keys

Getting cosmos db url and key
az : ERROR: az cosmosdb: 'keys' is not in the 'az cosmosdb' command group. See 'az cosmosdb --help'.
At C:\cosmos-db-scenario-based-labs-master\Retail\deploy\deploy.ps1:576 char:10
+ $res = $(az cosmosdb keys list --name $db.name --resource-group $rgNa ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: az cosmo...smosdb --help'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by givenscj** [comment]
I had some initial code, but it got out of hand for forcing an upgrade to latest Azure CLI.  We can revisit it later.  Right now it does tell them they need a min version in the pre-reqs/before the HOL.

**Comment by markjbrown** [comment]
Then if you could, make that text more obnoxious and large  :) and then include this PS cmd so they don't have to go searching for it. Just let them cut/paste it from there.

Thanks Chris.
