### ISSUE TITLE
[IOT Lab] Exercise 3 Intro - Incorrect Number of Functions

### ISSUE THREAD

**Issue by PlagueHO** [AzureCosmosDB/scenario-based-labs#56]
https://github.com/AzureCosmosDB/scenario-based-labs/blob/master/IoT/HOL%20step-by%20step%20-%20Cosmos%20DB%20scenario-based%20labs%20-%20IoT.md#exercise-3-deploy-azure-functions-and-web-app

Paragraph 3 reports "There are three Function Apps and one Web App in the solution."

There are only two functions apps as far as I can tell (the architecture does not show three function apps). There _are_ six functions, but two function apps.

**Comment by joelhulen** [comment]
Nice catch. Thanks!
