### ISSUE TITLE
Fatal Error accessing functions settings page

### ISSUE THREAD

**Issue by markjbrown** [AzureCosmosDB/scenario-based-labs#6]
Not sure what caused this error. Might be due to the incorrect az cli version which caused an error accessing cosmos db uri and key settings.

Getting the function app url and key
Action Requires: Opening url: https://portal.azure.com/#blade/WebsitesExtension/FunctionsIFrameBlade/id//subscriptions/220fc532-6091-423c-8ba0-66c2397d591b/resourceGrou
ps/mjb_s2_retail/providers/Microsoft.Web/sites/s2funcb6f53yxka32uw
Did you click to the function application's settings page yet?: y
The function app did not load the url, the host.json file is not available

**Comment by givenscj** [comment]
This is a interesting part of function app deployment.  You have to navigate to that page to have the backend create the master key file.  No real way around this that I know of.

**Comment by markjbrown** [comment]
Can you change the prompt there to just say. "Press enter when you have opened to this blade" or something like that. It's not clear whether the user has to enter some value.

btw, that's bizarre that this cannot be set with CLI.

**Comment by givenscj** [comment]
I added a loop to check for the master key rather than exiting the script.  Now users will have to explicitly end the script or get the master key created.
