### ISSUE TITLE
Allow user to select region to deploy resources

### ISSUE THREAD

**Issue by markjbrown** [AzureCosmosDB/scenario-based-labs#7]
This PS script forces users to deploy everything into West US region. This should be user driven using the list of regions I submitted as an issue in the IOT Lab so the user can choose which region to deploy it into.

**Comment by givenscj** [comment]
Updated.

**Comment by markjbrown** [comment]
@givenscj, I went through all the resource types and put together a list of regions where they are all GA. I posted it in the solliance repo. Can you use that list and include as a comment for the regions people can select? That will keep people from trying to deploy where the resource is not available.

Thanks.

**Comment by markjbrown** [comment]
Hi Chris. I am going through the Retail lab again and I don't see where this change is. In fact, I still see this in the deploy.ps1 script.

![image](https://user-images.githubusercontent.com/800166/66950567-7fbf5f00-f00d-11e9-8b78-a27b6d52b2e7.png)

**Comment by givenscj** [comment]
ARM templates are updated.   Script is updated to allow other regions now.  Next commit will provide regions tested.
