### ISSUE TITLE
Logic app hardcoded to West US 2

### ISSUE THREAD

**Issue by markjbrown** [AzureCosmosDB/scenario-based-labs#8]
This should be driven by a location parameter in labDeploy3.json

 "type": "Microsoft.Logic/workflows",
            "apiVersion": "2017-07-01",
            "name": "[variables('workflows_s2scenerio_name')]",
            "location": "westus2",
            "dependsOn": [

**Comment by givenscj** [comment]
Same as the other issue, updated to take dynamics regions from script.
