### ISSUE TITLE
ASA deployment should be driven by param file

### ISSUE THREAD

**Issue by markjbrown** [AzureCosmosDB/scenario-based-labs#9]
From deploy.ps1.

ASA deployment should be driven by parameter file so user can pass in location and any other details for deployment.

function SetupStreamAnalytics($suffix)
{
    #deploy the template
    $deployId = "Microsoft.Template"
    $result = $(az group deployment create --name $deployId --resource-group $rgName --mode Incremental --template-file $($githubpath + "\retail\deploy\labdeploy2.json") --output json )

**Comment by givenscj** [comment]
Added dynamic regions in all the latest ARM templates that take from the script variable.
